version: "3.7"

services:
  django-app:
    build:
      context: .
      dockerfile: ./deploy/apps/django.Dockerfile
    restart: always
    volumes:
      - static_volume:/project/static/
    env_file:
      - ./src/.env
    expose:
      - "8000"
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./src/.env
    expose:
      - "5432"

  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    env_file:
      - ./src/.env
    ports:
      - "5672"

  nginx:
    build:
      context: .
      dockerfile: ./deploy/nginx/nginx.Dockerfile
    restart: always
    volumes:
      - static_volume:/project/static/
    env_file:
      - ./src/.env
    expose:
      - "80"
    ports:
      - "8000:80"
    depends_on:
      - django-app
      - flower

  django-celery: &django_celery_default
    build:
      context: .
      dockerfile: ./deploy/apps/django.Dockerfile
    command: celery --app server.celery_app.celery_app worker -E --loglevel=info
    volumes:
      - static_volume:/project/static/
    env_file:
      - ./src/.env
    depends_on:
      - db
      - rabbitmq

  celery_beat:
    <<: *django_celery_default
    command: celery --app server.celery_app.celery_app beat --loglevel=info

  flask-celery-1: &flask_celery_default
    build:
      context: .
      dockerfile: ./deploy/apps/flask.Dockerfile
      args:
        - SERVICE_NUMBER=1
    command: celery --app main.celery_app worker -E --loglevel=info
    volumes:
      - static_volume:/project/static/
    env_file:
      - ./src/.env
    depends_on:
      - rabbitmq

  flask-celery-2:
    <<: *flask_celery_default
    build:
      context: .
      dockerfile: ./deploy/apps/flask.Dockerfile
      args:
        - SERVICE_NUMBER=2

  flower:
    image: mher/flower
    command: celery flower -l INFO
    restart: always
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq

volumes:
  postgres_data:
  static_volume:
  rabbitmq_data:
