# Generated by Django 4.2.9 on 2024-01-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False, verbose_name='Код')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Вино',
                'verbose_name_plural': 'Вина',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='WineTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(verbose_name='Идентификатор лога')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время запуска задачи')),
                ('sent_wine', models.PositiveIntegerField(null=True, verbose_name='Код отправленного вина')),
                ('expected_wine', models.PositiveIntegerField(null=True, verbose_name='Код ожидаемого вина')),
                ('received_wine', models.PositiveIntegerField(null=True, verbose_name='Код полученного вина')),
                ('is_coincided', models.BooleanField(default=False, verbose_name='Совпало')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи чейн-задач',
                'ordering': ('-created_at',),
            },
        ),
    ]
